// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: reval_service.proto
// Protobuf C++ Version: 5.29.0

#include "reval_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr GetEvalOperationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetEvalOperationRequest::GetEvalOperationRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetEvalOperationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetEvalOperationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetEvalOperationRequestDefaultTypeInternal() {}
  union {
    GetEvalOperationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetEvalOperationRequestDefaultTypeInternal _GetEvalOperationRequest_default_instance_;

inline constexpr EvalResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : interpreter_lines_{},
        svg_plots_{},
        status_{static_cast< ::EvalStatus >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EvalResult::EvalResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EvalResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EvalResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EvalResultDefaultTypeInternal() {}
  union {
    EvalResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EvalResultDefaultTypeInternal _EvalResult_default_instance_;

inline constexpr EvalRScriptRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : r_code_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EvalRScriptRequest::EvalRScriptRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EvalRScriptRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EvalRScriptRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EvalRScriptRequestDefaultTypeInternal() {}
  union {
    EvalRScriptRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EvalRScriptRequestDefaultTypeInternal _EvalRScriptRequest_default_instance_;

inline constexpr CancelEvalOperationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CancelEvalOperationRequest::CancelEvalOperationRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CancelEvalOperationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CancelEvalOperationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CancelEvalOperationRequestDefaultTypeInternal() {}
  union {
    CancelEvalOperationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CancelEvalOperationRequestDefaultTypeInternal _CancelEvalOperationRequest_default_instance_;

inline constexpr EvalErrorStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : details_{},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EvalErrorStatus::EvalErrorStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EvalErrorStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EvalErrorStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EvalErrorStatusDefaultTypeInternal() {}
  union {
    EvalErrorStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EvalErrorStatusDefaultTypeInternal _EvalErrorStatus_default_instance_;

inline constexpr EvalOperation::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        duration_{nullptr},
        done_{false},
        result_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR EvalOperation::EvalOperation(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EvalOperationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EvalOperationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EvalOperationDefaultTypeInternal() {}
  union {
    EvalOperation _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EvalOperationDefaultTypeInternal _EvalOperation_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_reval_5fservice_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_reval_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_reval_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::EvalRScriptRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::EvalRScriptRequest, _impl_.r_code_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::EvalErrorStatus, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::EvalErrorStatus, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::EvalErrorStatus, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::EvalErrorStatus, _impl_.details_),
        PROTOBUF_FIELD_OFFSET(::EvalOperation, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::EvalOperation, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::EvalOperation, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::EvalOperation, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::EvalOperation, _impl_.duration_),
        PROTOBUF_FIELD_OFFSET(::EvalOperation, _impl_.done_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::EvalOperation, _impl_.result_),
        ~0u,
        0,
        ~0u,
        ~0u,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GetEvalOperationRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GetEvalOperationRequest, _impl_.name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::CancelEvalOperationRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::CancelEvalOperationRequest, _impl_.name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::EvalResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::EvalResult, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::EvalResult, _impl_.interpreter_lines_),
        PROTOBUF_FIELD_OFFSET(::EvalResult, _impl_.svg_plots_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::EvalRScriptRequest)},
        {9, -1, -1, sizeof(::EvalErrorStatus)},
        {20, 34, -1, sizeof(::EvalOperation)},
        {39, -1, -1, sizeof(::GetEvalOperationRequest)},
        {48, -1, -1, sizeof(::CancelEvalOperationRequest)},
        {57, -1, -1, sizeof(::EvalResult)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_EvalRScriptRequest_default_instance_._instance,
    &::_EvalErrorStatus_default_instance_._instance,
    &::_EvalOperation_default_instance_._instance,
    &::_GetEvalOperationRequest_default_instance_._instance,
    &::_CancelEvalOperationRequest_default_instance_._instance,
    &::_EvalResult_default_instance_._instance,
};
const char descriptor_table_protodef_reval_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023reval_service.proto\032\033google/protobuf/e"
    "mpty.proto\032\036google/protobuf/duration.pro"
    "to\032\031google/protobuf/any.proto\"$\n\022EvalRSc"
    "riptRequest\022\016\n\006r_code\030\001 \001(\t\"W\n\017EvalError"
    "Status\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022%\n"
    "\007details\030\003 \003(\0132\024.google.protobuf.Any\"\251\001\n"
    "\rEvalOperation\022\014\n\004name\030\001 \001(\t\022+\n\010duration"
    "\030\002 \001(\0132\031.google.protobuf.Duration\022\014\n\004don"
    "e\030\003 \001(\010\022\"\n\013eval_result\030\004 \001(\0132\013.EvalResul"
    "tH\000\022!\n\005error\030\005 \001(\0132\020.EvalErrorStatusH\000B\010"
    "\n\006result\"\'\n\027GetEvalOperationRequest\022\014\n\004n"
    "ame\030\001 \001(\t\"*\n\032CancelEvalOperationRequest\022"
    "\014\n\004name\030\001 \001(\t\"W\n\nEvalResult\022\033\n\006status\030\001 "
    "\001(\0162\013.EvalStatus\022\031\n\021interpreter_lines\030\002 "
    "\003(\t\022\021\n\tsvg_plots\030\003 \003(\t*s\n\nEvalStatus\022\024\n\020"
    "EVAL_UNSPECIFIED\020\000\022\020\n\014EVAL_SUCCESS\020\001\022\025\n\021"
    "EVAL_R_CODE_ERROR\020\002\022\022\n\016EVAL_CPP_ERROR\020\003\022"
    "\022\n\016EVAL_CANCELLED\020\0042\314\001\n\014REvalService\0222\n\013"
    "EvalRScript\022\023.EvalRScriptRequest\032\016.EvalO"
    "peration\022<\n\020GetEvalOperation\022\030.GetEvalOp"
    "erationRequest\032\016.EvalOperation\022J\n\023Cancel"
    "EvalOperation\022\033.CancelEvalOperationReque"
    "st\032\026.google.protobuf.Emptyb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_reval_5fservice_2eproto_deps[3] =
    {
        &::descriptor_table_google_2fprotobuf_2fany_2eproto,
        &::descriptor_table_google_2fprotobuf_2fduration_2eproto,
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_reval_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_reval_5fservice_2eproto = {
    false,
    false,
    914,
    descriptor_table_protodef_reval_5fservice_2eproto,
    "reval_service.proto",
    &descriptor_table_reval_5fservice_2eproto_once,
    descriptor_table_reval_5fservice_2eproto_deps,
    3,
    6,
    schemas,
    file_default_instances,
    TableStruct_reval_5fservice_2eproto::offsets,
    file_level_enum_descriptors_reval_5fservice_2eproto,
    file_level_service_descriptors_reval_5fservice_2eproto,
};
const ::google::protobuf::EnumDescriptor* EvalStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_reval_5fservice_2eproto);
  return file_level_enum_descriptors_reval_5fservice_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t EvalStatus_internal_data_[] = {
    327680u, 0u, };
bool EvalStatus_IsValid(int value) {
  return 0 <= value && value <= 4;
}
// ===================================================================

class EvalRScriptRequest::_Internal {
 public:
};

EvalRScriptRequest::EvalRScriptRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:EvalRScriptRequest)
}
inline PROTOBUF_NDEBUG_INLINE EvalRScriptRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::EvalRScriptRequest& from_msg)
      : r_code_(arena, from.r_code_),
        _cached_size_{0} {}

EvalRScriptRequest::EvalRScriptRequest(
    ::google::protobuf::Arena* arena,
    const EvalRScriptRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EvalRScriptRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:EvalRScriptRequest)
}
inline PROTOBUF_NDEBUG_INLINE EvalRScriptRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : r_code_(arena),
        _cached_size_{0} {}

inline void EvalRScriptRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EvalRScriptRequest::~EvalRScriptRequest() {
  // @@protoc_insertion_point(destructor:EvalRScriptRequest)
  SharedDtor(*this);
}
inline void EvalRScriptRequest::SharedDtor(MessageLite& self) {
  EvalRScriptRequest& this_ = static_cast<EvalRScriptRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.r_code_.Destroy();
  this_._impl_.~Impl_();
}

inline void* EvalRScriptRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EvalRScriptRequest(arena);
}
constexpr auto EvalRScriptRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EvalRScriptRequest),
                                            alignof(EvalRScriptRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EvalRScriptRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EvalRScriptRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EvalRScriptRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EvalRScriptRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EvalRScriptRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EvalRScriptRequest>(), &EvalRScriptRequest::ByteSizeLong,
            &EvalRScriptRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EvalRScriptRequest, _impl_._cached_size_),
        false,
    },
    &EvalRScriptRequest::kDescriptorMethods,
    &descriptor_table_reval_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EvalRScriptRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2> EvalRScriptRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::EvalRScriptRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string r_code = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(EvalRScriptRequest, _impl_.r_code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string r_code = 1;
    {PROTOBUF_FIELD_OFFSET(EvalRScriptRequest, _impl_.r_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\6\0\0\0\0\0\0"
    "EvalRScriptRequest"
    "r_code"
  }},
};

PROTOBUF_NOINLINE void EvalRScriptRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:EvalRScriptRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.r_code_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EvalRScriptRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EvalRScriptRequest& this_ = static_cast<const EvalRScriptRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EvalRScriptRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EvalRScriptRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:EvalRScriptRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string r_code = 1;
          if (!this_._internal_r_code().empty()) {
            const std::string& _s = this_._internal_r_code();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EvalRScriptRequest.r_code");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:EvalRScriptRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EvalRScriptRequest::ByteSizeLong(const MessageLite& base) {
          const EvalRScriptRequest& this_ = static_cast<const EvalRScriptRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EvalRScriptRequest::ByteSizeLong() const {
          const EvalRScriptRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:EvalRScriptRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string r_code = 1;
            if (!this_._internal_r_code().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_r_code());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EvalRScriptRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EvalRScriptRequest*>(&to_msg);
  auto& from = static_cast<const EvalRScriptRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:EvalRScriptRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_r_code().empty()) {
    _this->_internal_set_r_code(from._internal_r_code());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EvalRScriptRequest::CopyFrom(const EvalRScriptRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EvalRScriptRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EvalRScriptRequest::InternalSwap(EvalRScriptRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.r_code_, &other->_impl_.r_code_, arena);
}

::google::protobuf::Metadata EvalRScriptRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EvalErrorStatus::_Internal {
 public:
};

void EvalErrorStatus::clear_details() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.details_.Clear();
}
EvalErrorStatus::EvalErrorStatus(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:EvalErrorStatus)
}
inline PROTOBUF_NDEBUG_INLINE EvalErrorStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::EvalErrorStatus& from_msg)
      : details_{visibility, arena, from.details_},
        message_(arena, from.message_),
        _cached_size_{0} {}

EvalErrorStatus::EvalErrorStatus(
    ::google::protobuf::Arena* arena,
    const EvalErrorStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EvalErrorStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.code_ = from._impl_.code_;

  // @@protoc_insertion_point(copy_constructor:EvalErrorStatus)
}
inline PROTOBUF_NDEBUG_INLINE EvalErrorStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : details_{visibility, arena},
        message_(arena),
        _cached_size_{0} {}

inline void EvalErrorStatus::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.code_ = {};
}
EvalErrorStatus::~EvalErrorStatus() {
  // @@protoc_insertion_point(destructor:EvalErrorStatus)
  SharedDtor(*this);
}
inline void EvalErrorStatus::SharedDtor(MessageLite& self) {
  EvalErrorStatus& this_ = static_cast<EvalErrorStatus&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* EvalErrorStatus::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EvalErrorStatus(arena);
}
constexpr auto EvalErrorStatus::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(EvalErrorStatus, _impl_.details_) +
          decltype(EvalErrorStatus::_impl_.details_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(EvalErrorStatus), alignof(EvalErrorStatus), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&EvalErrorStatus::PlacementNew_,
                                 sizeof(EvalErrorStatus),
                                 alignof(EvalErrorStatus));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EvalErrorStatus::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EvalErrorStatus_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EvalErrorStatus::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EvalErrorStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EvalErrorStatus::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EvalErrorStatus>(), &EvalErrorStatus::ByteSizeLong,
            &EvalErrorStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EvalErrorStatus, _impl_._cached_size_),
        false,
    },
    &EvalErrorStatus::kDescriptorMethods,
    &descriptor_table_reval_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EvalErrorStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 31, 2> EvalErrorStatus::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::EvalErrorStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EvalErrorStatus, _impl_.code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EvalErrorStatus, _impl_.code_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EvalErrorStatus, _impl_.message_)}},
    // repeated .google.protobuf.Any details = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(EvalErrorStatus, _impl_.details_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 code = 1;
    {PROTOBUF_FIELD_OFFSET(EvalErrorStatus, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(EvalErrorStatus, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .google.protobuf.Any details = 3;
    {PROTOBUF_FIELD_OFFSET(EvalErrorStatus, _impl_.details_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
  }}, {{
    "\17\0\7\0\0\0\0\0"
    "EvalErrorStatus"
    "message"
  }},
};

PROTOBUF_NOINLINE void EvalErrorStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:EvalErrorStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.details_.Clear();
  _impl_.message_.ClearToEmpty();
  _impl_.code_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EvalErrorStatus::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EvalErrorStatus& this_ = static_cast<const EvalErrorStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EvalErrorStatus::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EvalErrorStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:EvalErrorStatus)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 code = 1;
          if (this_._internal_code() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_code(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EvalErrorStatus.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // repeated .google.protobuf.Any details = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_details_size());
               i < n; i++) {
            const auto& repfield = this_._internal_details().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:EvalErrorStatus)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EvalErrorStatus::ByteSizeLong(const MessageLite& base) {
          const EvalErrorStatus& this_ = static_cast<const EvalErrorStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EvalErrorStatus::ByteSizeLong() const {
          const EvalErrorStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:EvalErrorStatus)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .google.protobuf.Any details = 3;
            {
              total_size += 1UL * this_._internal_details_size();
              for (const auto& msg : this_._internal_details()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // int32 code = 1;
            if (this_._internal_code() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_code());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EvalErrorStatus::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EvalErrorStatus*>(&to_msg);
  auto& from = static_cast<const EvalErrorStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:EvalErrorStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_details()->MergeFrom(
      from._internal_details());
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _this->_impl_.code_ = from._impl_.code_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EvalErrorStatus::CopyFrom(const EvalErrorStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EvalErrorStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EvalErrorStatus::InternalSwap(EvalErrorStatus* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.details_.InternalSwap(&other->_impl_.details_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.code_, other->_impl_.code_);
}

::google::protobuf::Metadata EvalErrorStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EvalOperation::_Internal {
 public:
  using HasBits =
      decltype(std::declval<EvalOperation>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::EvalOperation, _impl_._oneof_case_);
};

void EvalOperation::clear_duration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.duration_ != nullptr) _impl_.duration_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void EvalOperation::set_allocated_eval_result(::EvalResult* eval_result) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_result();
  if (eval_result) {
    ::google::protobuf::Arena* submessage_arena = eval_result->GetArena();
    if (message_arena != submessage_arena) {
      eval_result = ::google::protobuf::internal::GetOwnedMessage(message_arena, eval_result, submessage_arena);
    }
    set_has_eval_result();
    _impl_.result_.eval_result_ = eval_result;
  }
  // @@protoc_insertion_point(field_set_allocated:EvalOperation.eval_result)
}
void EvalOperation::set_allocated_error(::EvalErrorStatus* error) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_result();
  if (error) {
    ::google::protobuf::Arena* submessage_arena = error->GetArena();
    if (message_arena != submessage_arena) {
      error = ::google::protobuf::internal::GetOwnedMessage(message_arena, error, submessage_arena);
    }
    set_has_error();
    _impl_.result_.error_ = error;
  }
  // @@protoc_insertion_point(field_set_allocated:EvalOperation.error)
}
EvalOperation::EvalOperation(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:EvalOperation)
}
inline PROTOBUF_NDEBUG_INLINE EvalOperation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::EvalOperation& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_),
        result_{},
        _oneof_case_{from._oneof_case_[0]} {}

EvalOperation::EvalOperation(
    ::google::protobuf::Arena* arena,
    const EvalOperation& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EvalOperation* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.duration_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Duration>(
                              arena, *from._impl_.duration_)
                        : nullptr;
  _impl_.done_ = from._impl_.done_;
  switch (result_case()) {
    case RESULT_NOT_SET:
      break;
      case kEvalResult:
        _impl_.result_.eval_result_ = ::google::protobuf::Message::CopyConstruct<::EvalResult>(arena, *from._impl_.result_.eval_result_);
        break;
      case kError:
        _impl_.result_.error_ = ::google::protobuf::Message::CopyConstruct<::EvalErrorStatus>(arena, *from._impl_.result_.error_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:EvalOperation)
}
inline PROTOBUF_NDEBUG_INLINE EvalOperation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena),
        result_{},
        _oneof_case_{} {}

inline void EvalOperation::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, duration_),
           0,
           offsetof(Impl_, done_) -
               offsetof(Impl_, duration_) +
               sizeof(Impl_::done_));
}
EvalOperation::~EvalOperation() {
  // @@protoc_insertion_point(destructor:EvalOperation)
  SharedDtor(*this);
}
inline void EvalOperation::SharedDtor(MessageLite& self) {
  EvalOperation& this_ = static_cast<EvalOperation&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.duration_;
  if (this_.has_result()) {
    this_.clear_result();
  }
  this_._impl_.~Impl_();
}

void EvalOperation::clear_result() {
// @@protoc_insertion_point(one_of_clear_start:EvalOperation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (result_case()) {
    case kEvalResult: {
      if (GetArena() == nullptr) {
        delete _impl_.result_.eval_result_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.result_.eval_result_);
      }
      break;
    }
    case kError: {
      if (GetArena() == nullptr) {
        delete _impl_.result_.error_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.result_.error_);
      }
      break;
    }
    case RESULT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = RESULT_NOT_SET;
}


inline void* EvalOperation::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EvalOperation(arena);
}
constexpr auto EvalOperation::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EvalOperation),
                                            alignof(EvalOperation));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EvalOperation::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EvalOperation_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EvalOperation::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EvalOperation>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EvalOperation::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EvalOperation>(), &EvalOperation::ByteSizeLong,
            &EvalOperation::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_._cached_size_),
        false,
    },
    &EvalOperation::kDescriptorMethods,
    &descriptor_table_reval_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EvalOperation::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 5, 3, 26, 2> EvalOperation::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_._has_bits_),
    0, // no _extensions_
    5, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::EvalOperation>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_.name_)}},
    // .google.protobuf.Duration duration = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_.duration_)}},
    // bool done = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(EvalOperation, _impl_.done_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_.done_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Duration duration = 2;
    {PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_.duration_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool done = 3;
    {PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_.done_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // .EvalResult eval_result = 4;
    {PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_.result_.eval_result_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .EvalErrorStatus error = 5;
    {PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_.result_.error_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Duration>()},
    {::_pbi::TcParser::GetTable<::EvalResult>()},
    {::_pbi::TcParser::GetTable<::EvalErrorStatus>()},
  }}, {{
    "\15\4\0\0\0\0\0\0"
    "EvalOperation"
    "name"
  }},
};

PROTOBUF_NOINLINE void EvalOperation::Clear() {
// @@protoc_insertion_point(message_clear_start:EvalOperation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.duration_ != nullptr);
    _impl_.duration_->Clear();
  }
  _impl_.done_ = false;
  clear_result();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EvalOperation::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EvalOperation& this_ = static_cast<const EvalOperation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EvalOperation::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EvalOperation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:EvalOperation)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EvalOperation.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .google.protobuf.Duration duration = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.duration_, this_._impl_.duration_->GetCachedSize(), target,
                stream);
          }

          // bool done = 3;
          if (this_._internal_done() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_done(), target);
          }

          switch (this_.result_case()) {
            case kEvalResult: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  4, *this_._impl_.result_.eval_result_, this_._impl_.result_.eval_result_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kError: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  5, *this_._impl_.result_.error_, this_._impl_.result_.error_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:EvalOperation)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EvalOperation::ByteSizeLong(const MessageLite& base) {
          const EvalOperation& this_ = static_cast<const EvalOperation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EvalOperation::ByteSizeLong() const {
          const EvalOperation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:EvalOperation)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
           {
            // .google.protobuf.Duration duration = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.duration_);
            }
          }
           {
            // bool done = 3;
            if (this_._internal_done() != 0) {
              total_size += 2;
            }
          }
          switch (this_.result_case()) {
            // .EvalResult eval_result = 4;
            case kEvalResult: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.result_.eval_result_);
              break;
            }
            // .EvalErrorStatus error = 5;
            case kError: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.result_.error_);
              break;
            }
            case RESULT_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EvalOperation::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EvalOperation*>(&to_msg);
  auto& from = static_cast<const EvalOperation&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:EvalOperation)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.duration_ != nullptr);
    if (_this->_impl_.duration_ == nullptr) {
      _this->_impl_.duration_ =
          ::google::protobuf::Message::CopyConstruct<::google::protobuf::Duration>(arena, *from._impl_.duration_);
    } else {
      _this->_impl_.duration_->MergeFrom(*from._impl_.duration_);
    }
  }
  if (from._internal_done() != 0) {
    _this->_impl_.done_ = from._impl_.done_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_result();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kEvalResult: {
        if (oneof_needs_init) {
          _this->_impl_.result_.eval_result_ =
              ::google::protobuf::Message::CopyConstruct<::EvalResult>(arena, *from._impl_.result_.eval_result_);
        } else {
          _this->_impl_.result_.eval_result_->MergeFrom(from._internal_eval_result());
        }
        break;
      }
      case kError: {
        if (oneof_needs_init) {
          _this->_impl_.result_.error_ =
              ::google::protobuf::Message::CopyConstruct<::EvalErrorStatus>(arena, *from._impl_.result_.error_);
        } else {
          _this->_impl_.result_.error_->MergeFrom(from._internal_error());
        }
        break;
      }
      case RESULT_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EvalOperation::CopyFrom(const EvalOperation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EvalOperation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EvalOperation::InternalSwap(EvalOperation* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_.done_)
      + sizeof(EvalOperation::_impl_.done_)
      - PROTOBUF_FIELD_OFFSET(EvalOperation, _impl_.duration_)>(
          reinterpret_cast<char*>(&_impl_.duration_),
          reinterpret_cast<char*>(&other->_impl_.duration_));
  swap(_impl_.result_, other->_impl_.result_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata EvalOperation::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetEvalOperationRequest::_Internal {
 public:
};

GetEvalOperationRequest::GetEvalOperationRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GetEvalOperationRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetEvalOperationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GetEvalOperationRequest& from_msg)
      : name_(arena, from.name_),
        _cached_size_{0} {}

GetEvalOperationRequest::GetEvalOperationRequest(
    ::google::protobuf::Arena* arena,
    const GetEvalOperationRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetEvalOperationRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GetEvalOperationRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetEvalOperationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void GetEvalOperationRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetEvalOperationRequest::~GetEvalOperationRequest() {
  // @@protoc_insertion_point(destructor:GetEvalOperationRequest)
  SharedDtor(*this);
}
inline void GetEvalOperationRequest::SharedDtor(MessageLite& self) {
  GetEvalOperationRequest& this_ = static_cast<GetEvalOperationRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GetEvalOperationRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetEvalOperationRequest(arena);
}
constexpr auto GetEvalOperationRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetEvalOperationRequest),
                                            alignof(GetEvalOperationRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetEvalOperationRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetEvalOperationRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetEvalOperationRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetEvalOperationRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetEvalOperationRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetEvalOperationRequest>(), &GetEvalOperationRequest::ByteSizeLong,
            &GetEvalOperationRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetEvalOperationRequest, _impl_._cached_size_),
        false,
    },
    &GetEvalOperationRequest::kDescriptorMethods,
    &descriptor_table_reval_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetEvalOperationRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 36, 2> GetEvalOperationRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GetEvalOperationRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetEvalOperationRequest, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(GetEvalOperationRequest, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\4\0\0\0\0\0\0"
    "GetEvalOperationRequest"
    "name"
  }},
};

PROTOBUF_NOINLINE void GetEvalOperationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:GetEvalOperationRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetEvalOperationRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetEvalOperationRequest& this_ = static_cast<const GetEvalOperationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetEvalOperationRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetEvalOperationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GetEvalOperationRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GetEvalOperationRequest.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GetEvalOperationRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetEvalOperationRequest::ByteSizeLong(const MessageLite& base) {
          const GetEvalOperationRequest& this_ = static_cast<const GetEvalOperationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetEvalOperationRequest::ByteSizeLong() const {
          const GetEvalOperationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GetEvalOperationRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetEvalOperationRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetEvalOperationRequest*>(&to_msg);
  auto& from = static_cast<const GetEvalOperationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GetEvalOperationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetEvalOperationRequest::CopyFrom(const GetEvalOperationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GetEvalOperationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetEvalOperationRequest::InternalSwap(GetEvalOperationRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata GetEvalOperationRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CancelEvalOperationRequest::_Internal {
 public:
};

CancelEvalOperationRequest::CancelEvalOperationRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CancelEvalOperationRequest)
}
inline PROTOBUF_NDEBUG_INLINE CancelEvalOperationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::CancelEvalOperationRequest& from_msg)
      : name_(arena, from.name_),
        _cached_size_{0} {}

CancelEvalOperationRequest::CancelEvalOperationRequest(
    ::google::protobuf::Arena* arena,
    const CancelEvalOperationRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CancelEvalOperationRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:CancelEvalOperationRequest)
}
inline PROTOBUF_NDEBUG_INLINE CancelEvalOperationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void CancelEvalOperationRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CancelEvalOperationRequest::~CancelEvalOperationRequest() {
  // @@protoc_insertion_point(destructor:CancelEvalOperationRequest)
  SharedDtor(*this);
}
inline void CancelEvalOperationRequest::SharedDtor(MessageLite& self) {
  CancelEvalOperationRequest& this_ = static_cast<CancelEvalOperationRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CancelEvalOperationRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CancelEvalOperationRequest(arena);
}
constexpr auto CancelEvalOperationRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CancelEvalOperationRequest),
                                            alignof(CancelEvalOperationRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CancelEvalOperationRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CancelEvalOperationRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CancelEvalOperationRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CancelEvalOperationRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CancelEvalOperationRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CancelEvalOperationRequest>(), &CancelEvalOperationRequest::ByteSizeLong,
            &CancelEvalOperationRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CancelEvalOperationRequest, _impl_._cached_size_),
        false,
    },
    &CancelEvalOperationRequest::kDescriptorMethods,
    &descriptor_table_reval_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CancelEvalOperationRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 39, 2> CancelEvalOperationRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CancelEvalOperationRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CancelEvalOperationRequest, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(CancelEvalOperationRequest, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\4\0\0\0\0\0\0"
    "CancelEvalOperationRequest"
    "name"
  }},
};

PROTOBUF_NOINLINE void CancelEvalOperationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:CancelEvalOperationRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CancelEvalOperationRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CancelEvalOperationRequest& this_ = static_cast<const CancelEvalOperationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CancelEvalOperationRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CancelEvalOperationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:CancelEvalOperationRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CancelEvalOperationRequest.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:CancelEvalOperationRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CancelEvalOperationRequest::ByteSizeLong(const MessageLite& base) {
          const CancelEvalOperationRequest& this_ = static_cast<const CancelEvalOperationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CancelEvalOperationRequest::ByteSizeLong() const {
          const CancelEvalOperationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:CancelEvalOperationRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CancelEvalOperationRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CancelEvalOperationRequest*>(&to_msg);
  auto& from = static_cast<const CancelEvalOperationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CancelEvalOperationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CancelEvalOperationRequest::CopyFrom(const CancelEvalOperationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CancelEvalOperationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CancelEvalOperationRequest::InternalSwap(CancelEvalOperationRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata CancelEvalOperationRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EvalResult::_Internal {
 public:
};

EvalResult::EvalResult(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:EvalResult)
}
inline PROTOBUF_NDEBUG_INLINE EvalResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::EvalResult& from_msg)
      : interpreter_lines_{visibility, arena, from.interpreter_lines_},
        svg_plots_{visibility, arena, from.svg_plots_},
        _cached_size_{0} {}

EvalResult::EvalResult(
    ::google::protobuf::Arena* arena,
    const EvalResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EvalResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:EvalResult)
}
inline PROTOBUF_NDEBUG_INLINE EvalResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : interpreter_lines_{visibility, arena},
        svg_plots_{visibility, arena},
        _cached_size_{0} {}

inline void EvalResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
EvalResult::~EvalResult() {
  // @@protoc_insertion_point(destructor:EvalResult)
  SharedDtor(*this);
}
inline void EvalResult::SharedDtor(MessageLite& self) {
  EvalResult& this_ = static_cast<EvalResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* EvalResult::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EvalResult(arena);
}
constexpr auto EvalResult::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(EvalResult, _impl_.interpreter_lines_) +
          decltype(EvalResult::_impl_.interpreter_lines_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(EvalResult, _impl_.svg_plots_) +
          decltype(EvalResult::_impl_.svg_plots_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(EvalResult), alignof(EvalResult), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&EvalResult::PlacementNew_,
                                 sizeof(EvalResult),
                                 alignof(EvalResult));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EvalResult::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EvalResult_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EvalResult::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EvalResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EvalResult::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EvalResult>(), &EvalResult::ByteSizeLong,
            &EvalResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EvalResult, _impl_._cached_size_),
        false,
    },
    &EvalResult::kDescriptorMethods,
    &descriptor_table_reval_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EvalResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 45, 2> EvalResult::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::EvalResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .EvalStatus status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EvalResult, _impl_.status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EvalResult, _impl_.status_)}},
    // repeated string interpreter_lines = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EvalResult, _impl_.interpreter_lines_)}},
    // repeated string svg_plots = 3;
    {::_pbi::TcParser::FastUR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(EvalResult, _impl_.svg_plots_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .EvalStatus status = 1;
    {PROTOBUF_FIELD_OFFSET(EvalResult, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated string interpreter_lines = 2;
    {PROTOBUF_FIELD_OFFSET(EvalResult, _impl_.interpreter_lines_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string svg_plots = 3;
    {PROTOBUF_FIELD_OFFSET(EvalResult, _impl_.svg_plots_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\12\0\21\11\0\0\0\0"
    "EvalResult"
    "interpreter_lines"
    "svg_plots"
  }},
};

PROTOBUF_NOINLINE void EvalResult::Clear() {
// @@protoc_insertion_point(message_clear_start:EvalResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.interpreter_lines_.Clear();
  _impl_.svg_plots_.Clear();
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EvalResult::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EvalResult& this_ = static_cast<const EvalResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EvalResult::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EvalResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:EvalResult)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .EvalStatus status = 1;
          if (this_._internal_status() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_status(), target);
          }

          // repeated string interpreter_lines = 2;
          for (int i = 0, n = this_._internal_interpreter_lines_size(); i < n; ++i) {
            const auto& s = this_._internal_interpreter_lines().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EvalResult.interpreter_lines");
            target = stream->WriteString(2, s, target);
          }

          // repeated string svg_plots = 3;
          for (int i = 0, n = this_._internal_svg_plots_size(); i < n; ++i) {
            const auto& s = this_._internal_svg_plots().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EvalResult.svg_plots");
            target = stream->WriteString(3, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:EvalResult)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EvalResult::ByteSizeLong(const MessageLite& base) {
          const EvalResult& this_ = static_cast<const EvalResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EvalResult::ByteSizeLong() const {
          const EvalResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:EvalResult)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string interpreter_lines = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_interpreter_lines().size());
              for (int i = 0, n = this_._internal_interpreter_lines().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_interpreter_lines().Get(i));
              }
            }
            // repeated string svg_plots = 3;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_svg_plots().size());
              for (int i = 0, n = this_._internal_svg_plots().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_svg_plots().Get(i));
              }
            }
          }
           {
            // .EvalStatus status = 1;
            if (this_._internal_status() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EvalResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EvalResult*>(&to_msg);
  auto& from = static_cast<const EvalResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:EvalResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_interpreter_lines()->MergeFrom(from._internal_interpreter_lines());
  _this->_internal_mutable_svg_plots()->MergeFrom(from._internal_svg_plots());
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EvalResult::CopyFrom(const EvalResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EvalResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EvalResult::InternalSwap(EvalResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.interpreter_lines_.InternalSwap(&other->_impl_.interpreter_lines_);
  _impl_.svg_plots_.InternalSwap(&other->_impl_.svg_plots_);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata EvalResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_reval_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
